description = "BJCA Footstone Bpring Framework (Bill of Materials)"

apply plugin: 'java-platform'
apply from: "$rootDir/gradle/publications.gradle"

group = projectGroup

dependencies {
	constraints {
		parent.moduleProjects.sort { "$it.name" }.each {
			api it
		}
	}
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			artifactId = 'bjca-footstone-bpring-framework-bom'
			from components.javaPlatform
		}
	}
}