apply plugin: "maven-publish"

publishing {
	publications {
		mavenJava(MavenPublication) {
			pom {
				afterEvaluate {
					name = project.description?.replace("Spring", "BJCA Footstone Bpring")
					description = project.description?.replace("Spring", "BJCA Footstone Bpring")
				}
				url = "https://github.com/atbjca/spring-framework"
				organization {
					name = "BJCA"
					url = "https://github.com/atbjca"
				}
				licenses {
					license {
						name = "Apache License, Version 2.0"
						url = "https://www.apache.org/licenses/LICENSE-2.0"
						distribution = "repo"
					}
				}
				scm {
					url = "https://github.com/atbjca/spring-framework"
					connection = "scm:git:git://github.com/atbjca/spring-framework.git"
					developerConnection = "scm:git:git://github.com/atbjca/spring-framework.git"
				}
				developers {
					developer {
						id = "atbjca"
						name = "BJCA Footstone Team"
						email = ""
					}
				}
				issueManagement {
					system = "GitHub"
					url = "https://github.com/atbjca/spring-framework/issues"
				}
			}
			versionMapping {
				usage('java-api') {
					fromResolutionResult()
				}
				usage('java-runtime') {
					fromResolutionResult()
				}
			}
		}
	}
}

configureDeploymentRepository(project)

void configureDeploymentRepository(Project project) {
	project.plugins.withType(MavenPublishPlugin.class).all {
		PublishingExtension publishing = project.getExtensions().getByType(PublishingExtension.class);
		if (project.hasProperty("deploymentRepository")) {
			publishing.repositories.maven {
				it.url = project.property("deploymentRepository")
				it.name = "deployment"
			}
		}
	}
}